name: C/C++ CI

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
  
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: dewit
    - run: make
    - run: ./ischristmas
        

